language: csharp
mono: none
dotnet: 2.1.3

install:
- dotnet restore

script:
 - dotnet build -c Release
 - dotnet test Secp256k1.Net.Test -c Release

matrix:
  include:
    - os: linux
      env: 
        - OS=linux_x64
      dist: trusty

    - os: osx
      env:
        - OS=macos_x64